language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    - secure: "or4rMSxpTJcgefXVC6xzziLJeceTaZL6dCk3TSnDQvrW7WB50G2jUrniCLCNmAXdub9KY/CidsT+nvxw6SQAl7ey6cEFGwVs761vwNsdRypLmoMUawGsEjvVqh4u9BSwz8xCm5KzG9JcwCKkRd3GIQTYl20bHeRG1WlCr1wi4GZAFe1bSp80cy4y3HaQTeSIQTFxcZTNijeT7xWT2j4ZeiNIJ4eqWoQogzlWG0OzPLZYnmUzrhtxdZX9ceXKsT673zCh1L93Mt+jpRm1ZwPPIKHpKrNsW5Xr1t7eW+UULjzmDC+AYmItV37tKMFiMjeDPiFZRTBN93kzz744MOsh58ue0OzCRnrDVDcoEtXCPf4EKad6IyP86IvFySPpgi4gAx/Tr94kfKmDje6jcZcfLqV8xLm1gxPoxOOH7OOD4Y16tdPqCdp3vZx1vq6shkM2QbAHxd9ZnAv5Ey3szeRcrvhlJ0CJMM74bOjPHGT17jAkm6gLCo/RJN2TQvDAniWevKG+m+NCL1gnMsrfH0NuQi6aZNfBIlrzUsRQJEcypLqf82X3FrXla9r5KlVU+85Iw8frv0ViNw2a3I0m47IYODycld83AdSeiX4x0gurS+Cuqq9Nvm1qspoYKPG0E+u26K9mJRsEtuXFwzufaXPnq1oVo5N9HS6ii1OCtKo1WkQ="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
deploy:
  - provider: pages
    repo: konnectors/cozy-konnector-mgen
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    target-branch: build
    local-dir: ./build
    on:
      branch: master
  - provider: pages
    repo: konnectors/cozy-konnector-mgen
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    target-branch: latest
    local-dir: ./build
    on:
      branch: prod
